<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { apiFetch } from '@/utils/api';
const loading=ref(true),saving=ref(false),testing=ref(false),message=ref(''),error=ref('');
const form=ref({enabled:false,host:'smtp.mx.cloudflare.net',port:465,secure:true,username:'api_token',password:'',fromEmail:'',fromName:'BraTipsters'});
const testTo=ref('');
async function load(){loading.value=true;error.value='';try{const r=await apiFetch('/admin/email-settings');Object.assign(form.value,r);form.value.password='';}catch(e:any){error.value=e.message||'Unable to load settings';}finally{loading.value=false}}
async function save(){saving.value=true;message.value='';error.value='';try{const body:any={...form.value};if(!body.password)delete body.password;const r=await apiFetch('/admin/email-settings',{method:'PATCH',body:JSON.stringify(body)});Object.assign(form.value,r);form.value.password='';message.value='Email settings saved.';}catch(e:any){error.value=e.message||'Unable to save settings';}finally{saving.value=false}}
async function test(){testing.value=true;message.value='';error.value='';try{await apiFetch('/admin/email-settings/test',{method:'POST',body:JSON.stringify({to:testTo.value})},30000);message.value='Test email sent successfully.';}catch(e:any){error.value=e.message||'Test email failed';}finally{testing.value=false}}
onMounted(load);
</script>
<template><div><v-breadcrumbs :items="['Dashboard','Settings','Email Configuration']" class="px-0"/><v-card elevation="0" border><v-card-title>Cloudflare Email Configuration</v-card-title><v-card-subtitle>Use Cloudflare Email Service to send professional BraTipsters emails from your domain.</v-card-subtitle><v-card-text><v-alert type="info" variant="tonal" class="mb-5">Cloudflare Email Service SMTP uses <strong>smtp.mx.cloudflare.net</strong> on port <strong>465</strong> with implicit TLS. Your Cloudflare API token is used as the SMTP password and the username is automatically set to <strong>api_token</strong>.</v-alert><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-alert v-if="message" type="success" variant="tonal" class="mb-4">{{message}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-row v-else><v-col cols="12"><v-switch v-model="form.enabled" label="Enable transactional email" color="primary" hide-details/></v-col><v-col cols="12" md="8"><v-text-field v-model="form.host" label="Cloudflare SMTP host" placeholder="smtp.mx.cloudflare.net" variant="outlined" hint="Cloudflare Email Service SMTP endpoint" persistent-hint/></v-col><v-col cols="12" md="4"><v-text-field v-model.number="form.port" label="SMTP port" type="number" variant="outlined" hint="Cloudflare uses 465" persistent-hint/></v-col><v-col cols="12"><v-text-field v-model="form.password" label="Cloudflare API Token" type="password" placeholder="Paste your Cloudflare API token" variant="outlined" hint="The token must have Email Sending: Edit permission. It is stored encrypted." persistent-hint/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.fromName" label="From name" variant="outlined"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.fromEmail" label="From email" placeholder="hello@bratipsters.com" variant="outlined" hint="The domain must be onboarded in Cloudflare Email Sending." persistent-hint/></v-col></v-row><v-divider class="my-5"/><div class="text-subtitle-1 font-weight-bold mb-2">Send a test</div><div class="text-body-2 text-medium-emphasis mb-4">Save the Cloudflare configuration first, then send a test message.</div><v-row><v-col cols="12" md="8"><v-text-field v-model="testTo" label="Test recipient email" type="email" variant="outlined"/></v-col><v-col cols="12" md="4" class="d-flex align-center"><v-btn color="primary" :loading="testing" :disabled="!testTo" @click="test">Send test email</v-btn></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" :loading="saving" @click="save">Save email configuration</v-btn></v-card-actions></v-card></div></template>
