<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { apiFetch } from '@/utils/api';
const loading=ref(true),saving=ref(false),testing=ref(false),message=ref(''),error=ref('');
const form=ref({enabled:false,host:'',port:587,secure:false,username:'',password:'',fromEmail:'',fromName:'BraTipsters'});
const testTo=ref('');
async function load(){loading.value=true;error.value='';try{const r=await apiFetch('/admin/email-settings');Object.assign(form.value,r);form.value.password='';}catch(e:any){error.value=e.message||'Unable to load settings';}finally{loading.value=false}}
async function save(){saving.value=true;message.value='';error.value='';try{const body:any={...form.value};if(!body.password)delete body.password;const r=await apiFetch('/admin/email-settings',{method:'PATCH',body:JSON.stringify(body)});Object.assign(form.value,r);form.value.password='';message.value='Email settings saved.';}catch(e:any){error.value=e.message||'Unable to save settings';}finally{saving.value=false}}
async function test(){testing.value=true;message.value='';error.value='';try{await apiFetch('/admin/email-settings/test',{method:'POST',body:JSON.stringify({to:testTo.value})});message.value='Test email sent successfully.';}catch(e:any){error.value=e.message||'Test email failed';}finally{testing.value=false}}
onMounted(load);
</script>
<template><div><v-breadcrumbs :items="['Dashboard','Settings','Email Configuration']" class="px-0"/><v-card elevation="0" border><v-card-title>Professional Email Configuration</v-card-title><v-card-subtitle>Configure SMTP for branded BraTipsters emails such as account welcome messages, tipster application decisions and payout updates.</v-card-subtitle><v-card-text><v-alert type="info" variant="tonal" class="mb-5">Your Cloudflare domain provides DNS and domain management; outbound email still needs an SMTP mailbox/provider. Use a provider such as Zoho Mail, Google Workspace, Brevo, Resend SMTP, or another SMTP service, then enter its SMTP details here.</v-alert><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-alert v-if="message" type="success" variant="tonal" class="mb-4">{{message}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-row v-else><v-col cols="12"><v-switch v-model="form.enabled" label="Enable transactional email" color="primary" hide-details/></v-col><v-col cols="12" md="8"><v-text-field v-model="form.host" label="SMTP host" placeholder="smtp.yourmailprovider.com" variant="outlined"/></v-col><v-col cols="12" md="4"><v-text-field v-model.number="form.port" label="SMTP port" type="number" variant="outlined"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.username" label="SMTP username" variant="outlined"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.password" label="SMTP password" type="password" placeholder="Leave blank to keep existing password" variant="outlined"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.fromName" label="From name" variant="outlined"/></v-col><v-col cols="12" md="6"><v-text-field v-model="form.fromEmail" label="From email" placeholder="hello@bratipsters.com" variant="outlined"/></v-col><v-col cols="12"><v-switch v-model="form.secure" label="Use SSL/TLS (secure SMTP)" color="primary" hide-details/></v-col></v-row><v-divider class="my-5"/><div class="text-subtitle-1 font-weight-bold mb-2">Send a test</div><div class="text-body-2 text-medium-emphasis mb-4">Save the SMTP configuration first, then send a test message to confirm delivery.</div><v-row><v-col cols="12" md="8"><v-text-field v-model="testTo" label="Test recipient email" type="email" variant="outlined"/></v-col><v-col cols="12" md="4" class="d-flex align-center"><v-btn color="primary" :loading="testing" :disabled="!testTo" @click="test">Send test email</v-btn></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" :loading="saving" @click="save">Save email configuration</v-btn></v-card-actions></v-card></div></template>
