<script setup lang="ts">
import { ref,onMounted } from 'vue'; import { apiFetch } from '@/utils/api';
const date=ref(new Date().toISOString().slice(0,10)),rows=ref<any[]>([]),loading=ref(false),error=ref('');
async function load(){try{rows.value=await apiFetch(`/admin/bet-of-day?date=${date.value}`)}catch(e:any){error.value=e.message}}
async function generate(){loading.value=true;error.value='';try{rows.value=await apiFetch('/admin/bet-of-day/generate',{method:'POST',body:JSON.stringify({date:date.value})})}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function status(id:string,status:string){try{await apiFetch(`/admin/bet-of-day/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><v-card elevation="0" class="border rounded-lg"><v-card-item><template #prepend><div><v-card-title>AI Bet of the Day</v-card-title><v-card-subtitle>Automatically selected and published daily from available fixtures, markets and odds. Admin review is no longer required.</v-card-subtitle></div></template><template #append><div class="d-flex ga-2"><v-text-field v-model="date" type="date" density="compact" variant="outlined" hide-details/><v-btn color="primary" :loading="loading" @click="generate">Run Automatic Selection</v-btn></div></template></v-card-item><v-card-text><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-row><v-col v-for="r in rows" :key="r._id" cols="12" md="6"><v-card variant="tonal"><v-card-item><v-card-title>{{r.matchId?.homeTeamId?.name}} vs {{r.matchId?.awayTeamId?.name}}</v-card-title><v-card-subtitle>{{r.matchId?.leagueId?.name}} · {{r.matchId?.kickoff?new Date(r.matchId.kickoff).toLocaleString():''}}</v-card-subtitle></v-card-item><v-card-text><div class="text-h6">{{r.prediction}}</div><div class="mt-2">Confidence: <b>{{r.confidence}}%</b> · Risk: <b>{{r.risk}}</b></div><p class="mt-3">{{r.analysis}}</p><v-chip size="small">{{r.model}}</v-chip><v-chip size="small" class="ml-2">{{r.status}}</v-chip></v-card-text><v-card-actions><v-chip v-if="r.status==='published'" color="success" variant="tonal">Live on public site</v-chip></v-card-actions></v-card></v-col></v-row><div v-if="!rows.length" class="text-center py-8">No picks generated for this date.</div></v-card-text></v-card></template>
