<script setup lang="ts">
import { ref, onMounted } from 'vue'; import { apiFetch } from '@/utils/api';
const loading=ref(false), error=ref(''), message=ref(''), status=ref<any>(null), date=ref(new Date().toISOString().slice(0,10));
async function load(){try{status.value=await apiFetch('/admin/sync/status')}catch(e:any){error.value=e.message}}
async function run(type:'live'|'daily'){loading.value=true;error.value='';message.value='';try{const d=await apiFetch('/admin/sync/run',{method:'POST',body:JSON.stringify({type,date:date.value})});message.value=`${type==='live'?'Live':'Daily'} sync completed: ${d.fetched} fetched, ${d.upserted} saved.`;await load()}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function runDaily(){loading.value=true;error.value='';try{const d=await apiFetch('/admin/sync/run-daily',{method:'POST',body:JSON.stringify({date:date.value})});message.value=`Daily sync completed and Bet of the Day generated (${d.picks?.length||0} picks).`;await load()}catch(e:any){error.value=e.message}finally{loading.value=false}}
onMounted(load)
</script>
<template><v-row><v-col cols="12"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Automatic Data Sync</v-card-title><v-card-subtitle>Football sync runs automatically in the backend. Use these controls for admin overrides.</v-card-subtitle></v-card-item><v-card-text><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-alert v-if="message" type="success" variant="tonal" class="mb-4">{{message}}</v-alert><div class="d-flex flex-wrap ga-3 align-center"><v-text-field v-model="date" type="date" label="Date" variant="outlined" density="comfortable" hide-details style="max-width:220px"/><v-btn color="primary" :loading="loading" @click="runDaily">Run Daily Sync + Generate Picks</v-btn><v-btn variant="tonal" :loading="loading" @click="run('live')">Sync Live Now</v-btn><v-btn variant="tonal" :loading="loading" @click="run('daily')">Sync Date Now</v-btn></div></v-card-text></v-card></v-col><v-col cols="12"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Sync History</v-card-title></v-card-item><v-card-text><v-table><thead><tr><th>Type</th><th>Status</th><th>Started</th><th>Finished</th><th>Fetched</th><th>Saved</th><th>Error</th></tr></thead><tbody><tr v-for="j in status?.history||[]" :key="j._id"><td>{{j.type}}</td><td><v-chip size="small" :color="j.status==='success'?'success':j.status==='failed'?'error':'warning'">{{j.status}}</v-chip></td><td>{{new Date(j.startedAt).toLocaleString()}}</td><td>{{j.finishedAt?new Date(j.finishedAt).toLocaleString():'—'}}</td><td>{{j.fetched}}</td><td>{{j.upserted}}</td><td>{{j.error||'—'}}</td></tr></tbody></v-table></v-card-text></v-card></v-col></v-row></template>
