<script setup lang="ts">
import { onMounted, ref, computed } from 'vue'; import { apiFetch } from '@/utils/api';
const rows=ref<any[]>([]),loading=ref(false),error=ref(''),search=ref(''),editing=ref<any|null>(null),saving=ref(false);
const filtered=computed(()=>{const q=search.value.toLowerCase().trim();return rows.value.filter(r=>!q||`${r.name} ${r.email} ${r.role} ${r.status}`.toLowerCase().includes(q))});
async function load(){loading.value=true;try{rows.value=await apiFetch('/admin/users?limit=100')}catch(e:any){error.value=e.message}finally{loading.value=false}}
function edit(r:any){editing.value={...r}}
async function save(){if(!editing.value)return;saving.value=true;try{await apiFetch(`/admin/users/${editing.value._id}`,{method:'PATCH',body:JSON.stringify({name:editing.value.name,role:editing.value.role,status:editing.value.status})});editing.value=null;await load()}catch(e:any){error.value=e.message}finally{saving.value=false}} onMounted(load)
</script>
<template><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Users</v-card-title><v-card-subtitle>Manage account role and access status.</v-card-subtitle></v-card-item><v-card-text><v-text-field v-model="search" label="Search users" prepend-inner-icon="mdi-magnify" variant="outlined" clearable class="mb-4"/><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-table v-else><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th/></tr></thead><tbody><tr v-for="r in filtered" :key="r._id"><td>{{r.name}}</td><td>{{r.email}}</td><td>{{r.role}}</td><td><v-chip size="small" :color="r.status==='active'?'success':'error'">{{r.status}}</v-chip></td><td><v-btn variant="text" color="primary" @click="edit(r)">Edit</v-btn></td></tr></tbody></v-table></v-card-text></v-card><v-dialog :model-value="!!editing" @update:model-value="v=>{if(!v)editing=null}" max-width="520"><v-card v-if="editing"><v-card-title>Edit User</v-card-title><v-card-text><v-text-field v-model="editing.name" label="Name" variant="outlined"/><v-select v-model="editing.role" :items="['user','tipster','admin']" label="Role" variant="outlined"/><v-select v-model="editing.status" :items="['active','suspended']" label="Status" variant="outlined"/></v-card-text><v-card-actions><v-spacer/><v-btn variant="text" @click="editing=null">Cancel</v-btn><v-btn color="primary" :loading="saving" @click="save">Save</v-btn></v-card-actions></v-card></v-dialog></template>
