<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { apiFetch } from '@/utils/api';
const fixtures=ref<any[]>([]), selected=ref(''), data=ref<any>(null), loading=ref(false), error=ref('');
async function loadFixtures(){try{const d=await apiFetch('/admin/providers/fixtures');fixtures.value=Array.isArray(d?.data)?d.data:[];if(fixtures.value[0])selected.value=String(fixtures.value[0].id)}catch(e:any){error.value=e.message}}
async function loadXg(){if(!selected.value)return;loading.value=true;error.value='';try{data.value=await apiFetch(`/admin/providers/xgoals/${selected.value}`)}catch(e:any){error.value=e.message;data.value=null}finally{loading.value=false}}
onMounted(async()=>{await loadFixtures();await loadXg()})
</script>
<template><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Sportmonks xGoals</v-card-title><v-card-subtitle>Expected goals and related metrics for a selected fixture.</v-card-subtitle><template #append><div class="d-flex ga-2"><v-select v-model="selected" :items="fixtures.map((f:any)=>({title:f.name,value:String(f.id)}))" density="compact" variant="outlined" hide-details style="min-width:280px" @update:model-value="loadXg"/><v-btn variant="tonal" @click="loadXg">Refresh</v-btn></div></template></v-card-item><v-card-text><v-alert v-if="error" type="warning" variant="tonal" class="mb-4">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate/><div v-if="data&&!loading"><v-row><v-col cols="12" md="6"><v-card variant="tonal"><v-card-item><v-card-title>{{data.name||'Fixture'}}</v-card-title><v-card-subtitle>{{data.starting_at||''}}</v-card-subtitle></v-card-item><v-card-text><div v-for="x in (data.xgfixture||[])" :key="x.id||JSON.stringify(x)"><b>{{x.type?.name||x.type?.developer_name||'xG'}}</b> — {{x.location||''}}: {{x.data?.value ?? '—'}}</div></v-card-text></v-card></v-col><v-col cols="12" md="6"><pre class="provider-json">{{JSON.stringify(data,null,2)}}</pre></v-col></v-row></div></v-card-text></v-card></template>
<style scoped>.provider-json{white-space:pre-wrap;word-break:break-word;max-height:500px;overflow:auto;background:rgba(0,0,0,.03);padding:16px;border-radius:8px}</style>
