<script setup lang="ts">
import {onMounted,ref} from 'vue'; import {BellOutlined,CheckCircleOutlined} from '@ant-design/icons-vue'; import {apiFetch} from '@/utils/api';
const items=ref<any[]>([]),unread=ref(0),loading=ref(false),open=ref(false);
async function load(){try{const d=await apiFetch('/me/notifications');items.value=d.data||d;unread.value=d.unread||items.value.filter((x:any)=>!x.read).length}catch{}}
async function read(n:any){if(n.read)return;await apiFetch(`/me/notifications/${n._id}/read`,{method:'PATCH',body:JSON.stringify({})});n.read=true;unread.value=Math.max(0,unread.value-1)}
async function all(){loading.value=true;try{await apiFetch('/me/notifications/read-all',{method:'PATCH',body:JSON.stringify({})});items.value.forEach(x=>x.read=true);unread.value=0}finally{loading.value=false}}
function refresh(){load()} onMounted(load);
</script>
<template><v-menu v-model="open" :close-on-content-click="false" offset="8"><template #activator="{props}"><v-btn v-bind="props" icon variant="text"><v-badge :content="unread" :model-value="unread>0" color="primary"><BellOutlined/></v-badge></v-btn></template><v-card width="390"><v-card-item><div class="d-flex justify-space-between align-center"><v-card-title class="pa-0">Notifications</v-card-title><v-btn size="small" variant="text" :loading="loading" @click="all"><CheckCircleOutlined/> Mark all read</v-btn></div></v-card-item><v-divider/><v-list v-if="items.length" lines="two"><v-list-item v-for="n in items" :key="n._id" :class="{unread:!n.read}" @click="read(n)"><v-list-item-title>{{n.title}}</v-list-item-title><v-list-item-subtitle>{{n.message}}</v-list-item-subtitle><template #append><span class="text-caption">{{new Date(n.createdAt).toLocaleDateString()}}</span></template></v-list-item></v-list><div v-else class="pa-8 text-center text-medium-emphasis">No notifications yet.</div><v-divider/><v-card-actions><v-btn block variant="text" @click="refresh">Refresh</v-btn></v-card-actions></v-card></v-menu></template><style scoped>.unread{background:rgba(99,102,241,.06)}</style>
