<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { apiFetch } from '@/utils/api';
const days=ref(30), loading=ref(false), error=ref(''), data=ref<any>({totals:{},userSeries:[],predictionSeries:[],matchStatuses:[],predictionStatuses:[],topTipsters:[]});
const labels=computed(()=>data.value.userSeries.map((x:any)=>x._id));
const usersSeries=computed(()=>[{name:'New users',data:data.value.userSeries.map((x:any)=>x.count)}]);
const predictionSeries=computed(()=>[{name:'Predictions',data:data.value.predictionSeries.map((x:any)=>x.count)},{name:'Profit',data:data.value.predictionSeries.map((x:any)=>Number(x.profit||0))}]);
const lineOptions=computed(()=>({chart:{toolbar:{show:false}},stroke:{curve:'smooth'},xaxis:{categories:labels.value}}));
async function load(){loading.value=true;error.value='';try{data.value=await apiFetch(`/admin/analytics/overview?days=${days.value}`)}catch(e:any){error.value=e.message}finally{loading.value=false}}
onMounted(load)
</script>
<template><v-row><v-col cols="12"><v-card elevation="0" class="border rounded-lg"><v-card-item><template #prepend><div><v-card-title>Platform Analytics</v-card-title><v-card-subtitle>Live metrics from BraTips MongoDB.</v-card-subtitle></div></template><template #append><v-select v-model="days" :items="[7,30,90,180,365]" suffix="days" density="compact" variant="outlined" hide-details @update:model-value="load"/></template></v-card-item><v-alert v-if="error" type="error" variant="tonal" class="ma-4">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-card-text><v-row><v-col v-for="(value,key) in data.totals" :key="key" cols="6" md="2"><div class="text-caption text-medium-emphasis text-capitalize">{{String(key).replace(/([A-Z])/g,' $1')}}</div><div class="text-h4 font-weight-bold">{{value}}</div></v-col></v-row></v-card-text></v-card></v-col><v-col cols="12" lg="6"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>User Growth</v-card-title></v-card-item><v-card-text><apexchart type="area" height="300" :options="lineOptions" :series="usersSeries"/></v-card-text></v-card></v-col><v-col cols="12" lg="6"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Prediction Activity</v-card-title></v-card-item><v-card-text><apexchart type="line" height="300" :options="lineOptions" :series="predictionSeries"/></v-card-text></v-card></v-col><v-col cols="12" lg="6"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Top Tipsters</v-card-title></v-card-item><v-card-text><v-table><thead><tr><th>Tipster</th><th>Tips</th><th>Wins</th><th>Profit</th><th>ROI</th></tr></thead><tbody><tr v-for="t in data.topTipsters" :key="t._id"><td>{{t.username}}</td><td>{{t.totalTips}}</td><td>{{t.wins}}</td><td>{{t.profit}}</td><td>{{t.roi}}%</td></tr></tbody></v-table></v-card-text></v-card></v-col><v-col cols="12" lg="6"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Match Status</v-card-title></v-card-item><v-card-text><v-chip v-for="m in data.matchStatuses" :key="m._id" class="ma-1" variant="tonal">{{m._id}}: {{m.count}}</v-chip></v-card-text></v-card></v-col></v-row></template>
