<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { apiFetch } from '@/utils/api';
const rows=ref<any[]>([]), loading=ref(false), error=ref(''), search=ref(''), status=ref(''), selected=ref<any|null>(null), notes=ref(''), reviewLoading=ref(false);
const filtered=computed(()=>{const q=search.value.toLowerCase().trim();return rows.value.filter(r=>(!status.value||r.status===status.value)&&(!q||`${r.username} ${r.userId?.name||''} ${r.userId?.email||''}`.toLowerCase().includes(q)))})
async function load(){loading.value=true;try{const d=await apiFetch('/admin/tipster-applications');rows.value=d.data||d||[]}catch(e:any){error.value=e.message}finally{loading.value=false}}
function open(row:any){selected.value=row;notes.value=row.adminNotes||''}
async function review(action:string){if(!selected.value)return;reviewLoading.value=true;try{await apiFetch(`/admin/tipster-applications/${selected.value._id}/review`,{method:'PATCH',body:JSON.stringify({action,adminNotes:notes.value})});selected.value=null;await load()}catch(e:any){error.value=e.message}finally{reviewLoading.value=false}}
function badgeColor(s:string){return s==='approved'?'success':s==='rejected'?'error':s==='suspended'?'error':s==='more_info'?'warning':s==='under_review'?'info':'primary'}
onMounted(load)
</script>
<template><v-card elevation="0" class="border rounded-lg"><v-card-item><template #prepend><div><v-card-title>Tipster Applications</v-card-title><v-card-subtitle>Review applicants and their required sample prediction.</v-card-subtitle></div></template></v-card-item><v-card-text><v-row><v-col cols="12" md="8"><v-text-field v-model="search" label="Search applicants" prepend-inner-icon="mdi-magnify" variant="outlined" clearable/></v-col><v-col cols="12" md="4"><v-select v-model="status" label="Status" variant="outlined" clearable :items="['pending','under_review','more_info','approved','rejected','suspended']"/></v-col></v-row><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate/><v-table v-else><thead><tr><th>Applicant</th><th>Username</th><th>Sample Tip</th><th>Odds</th><th>Status</th><th>Date</th><th/></tr></thead><tbody><tr v-for="r in filtered" :key="r._id"><td><div class="font-weight-bold">{{r.userId?.name}}</div><div class="text-caption">{{r.userId?.email}}</div></td><td>{{r.username}}</td><td>{{r.samplePrediction?.fixture}} — {{r.samplePrediction?.prediction}}</td><td>{{r.samplePrediction?.odds}}</td><td><v-chip size="small" :color="badgeColor(r.status)">{{r.status}}</v-chip></td><td>{{new Date(r.createdAt).toLocaleDateString()}}</td><td><v-btn size="small" color="primary" variant="text" @click="open(r)">Review</v-btn></td></tr><tr v-if="!filtered.length"><td colspan="7" class="text-center py-8">No applications found.</td></tr></tbody></v-table></v-card-text></v-card>
<v-dialog :model-value="!!selected" @update:model-value="v=>{if(!v)selected=null}" max-width="850"><v-card v-if="selected"><v-card-title class="d-flex align-center">Tipster Application <v-spacer/><v-chip :color="badgeColor(selected.status)">{{selected.status}}</v-chip></v-card-title><v-card-text><v-row><v-col cols="12" md="6"><v-card variant="tonal"><v-card-title>Applicant</v-card-title><v-card-text><div><b>Name:</b> {{selected.userId?.name}}</div><div><b>Email:</b> {{selected.userId?.email}}</div><div><b>Username:</b> {{selected.username}}</div><div><b>Country:</b> {{selected.country||'—'}}</div><div><b>Experience:</b> {{selected.experience||'—'}}</div><div><b>Expertise:</b> {{selected.expertise?.join(', ')||'—'}}</div><p class="mt-3"><b>Bio:</b><br/>{{selected.bio}}</p></v-card-text></v-card></v-col><v-col cols="12" md="6"><v-card variant="tonal"><v-card-title>Sample Prediction</v-card-title><v-card-text><div><b>Fixture:</b> {{selected.samplePrediction?.fixture}}</div><div><b>League:</b> {{selected.samplePrediction?.league||'—'}}</div><div><b>Prediction:</b> {{selected.samplePrediction?.prediction}}</div><div><b>Odds:</b> {{selected.samplePrediction?.odds}}</div><div><b>Confidence:</b> {{selected.samplePrediction?.confidence ?? '—'}}%</div><p class="mt-3"><b>Analysis:</b><br/>{{selected.samplePrediction?.analysis}}</p></v-card-text></v-card></v-col></v-row><v-textarea v-model="notes" label="Admin review notes" variant="outlined" class="mt-4"/><div class="d-flex flex-wrap ga-2"><v-btn color="info" :loading="reviewLoading" @click="review('under_review')">Under Review</v-btn><v-btn color="success" :loading="reviewLoading" @click="review('approve')">Approve</v-btn><v-btn color="warning" :loading="reviewLoading" @click="review('more_info')">Request More Info</v-btn><v-btn color="error" :loading="reviewLoading" @click="review('reject')">Reject</v-btn><v-btn color="error" variant="outlined" :loading="reviewLoading" @click="review('suspend')">Suspend</v-btn></div></v-card-text><v-card-actions><v-spacer/><v-btn variant="text" @click="selected=null">Close</v-btn></v-card-actions></v-card></v-dialog></template>
