<script setup lang="ts">
import { ref,onMounted } from 'vue'; import { apiFetch } from '@/utils/api';
const rules=ref<any[]>([]),ledger=ref<any[]>([]),summary=ref<any>({}),error=ref(''),loading=ref(false),dialog=ref(false),form=ref<any>({name:'',streak:3,amount:50,currency:'GHS',active:true});
async function load(){loading.value=true;try{rules.value=await apiFetch('/admin/rewards/rules');ledger.value=await apiFetch('/admin/rewards/ledger');summary.value=await apiFetch('/admin/rewards/summary')}catch(e:any){error.value=e.message}finally{loading.value=false}}
function open(){form.value={name:'',streak:3,amount:50,currency:'GHS',active:true};dialog.value=true}
async function save(){try{await apiFetch('/admin/rewards/rules',{method:'POST',body:JSON.stringify(form.value)});dialog.value=false;await load()}catch(e:any){error.value=e.message}}
async function setStatus(id:string,status:string){try{await apiFetch(`/admin/rewards/ledger/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><v-row><v-col cols="12"><v-card elevation="0" class="border rounded-lg"><v-card-item><template #prepend><div><v-card-title>Tipster Prize Rules</v-card-title><v-card-subtitle>Configure real-money rewards for settled winning streaks.</v-card-subtitle></div></template><template #append><v-btn color="primary" @click="open">Add Rule</v-btn></template></v-card-item><v-card-text><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-table><thead><tr><th>Name</th><th>Winning streak</th><th>Reward</th><th>Active</th></tr></thead><tbody><tr v-for="r in rules" :key="r._id"><td>{{r.name}}</td><td>{{r.streak}}</td><td>{{r.amount}} {{r.currency}}</td><td><v-switch v-model="r.active" hide-details density="compact" @update:model-value="apiFetch(`/admin/rewards/rules/${r._id}`,{method:'PATCH',body:JSON.stringify({active:r.active})})"/></td></tr></tbody></v-table></v-card-text></v-card></v-col><v-col cols="12"><v-row><v-col v-for="(v,k) in summary" :key="k" cols="12" md="4"><v-card variant="tonal"><v-card-text><div class="text-caption text-capitalize">{{k}}</div><div class="text-h5">{{v.amount||0}} GHS</div><div class="text-caption">{{v.count||0}} records</div></v-card-text></v-card></v-col></v-row></v-col><v-col cols="12"><v-card elevation="0" class="border rounded-lg"><v-card-item><v-card-title>Reward Ledger</v-card-title></v-card-item><v-card-text><v-table><thead><tr><th>Tipster</th><th>Streak</th><th>Rule</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="r in ledger" :key="r._id"><td>{{r.tipsterId?.username||r.tipsterId?.userId?.name||'—'}}</td><td>{{r.streak}}</td><td>{{r.ruleId?.name}}</td><td>{{r.amount}} {{r.currency}}</td><td>{{r.status}}</td><td><v-btn v-if="r.status==='pending'" size="small" @click="setStatus(r._id,'approved')">Approve</v-btn><v-btn v-if="r.status==='approved'" size="small" color="success" @click="setStatus(r._id,'paid')">Mark Paid</v-btn></td></tr></tbody></v-table></v-card-text></v-card></v-col></v-row><v-dialog v-model="dialog" max-width="520"><v-card><v-card-title>New Reward Rule</v-card-title><v-card-text><v-text-field v-model="form.name" label="Name"/><v-text-field v-model.number="form.streak" type="number" label="Winning streak"/><v-text-field v-model.number="form.amount" type="number" label="Reward amount"/><v-text-field v-model="form.currency" label="Currency"/></v-card-text><v-card-actions><v-spacer/><v-btn @click="dialog=false">Cancel</v-btn><v-btn color="primary" :loading="loading" @click="save">Save</v-btn></v-card-actions></v-card></v-dialog></template>
