<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { apiFetch } from '@/utils/api';

const strategy=ref<any>({platformSharePercent:70,tipsterPoolPercent:30,minSettledPredictions:50,minWithdrawal:10,currency:'GHS'});
const periods=ref<any[]>([]), rewards=ref<any[]>([]), withdrawals=ref<any[]>([]), revenue=ref<any>({total:{amount:0,count:0},byCurrency:[],byMonth:[]});
const error=ref(''),loading=ref(false),calculating=ref(false),savingStrategy=ref(false),month=ref(new Date().toISOString().slice(0,7));
const platformPercent=ref(70),poolPercent=ref(30);
const eligibleRewards=computed(()=>rewards.value.filter(r=>r.amount>0));
const pendingRewards=computed(()=>rewards.value.filter(r=>r.status==='pending'));
const pendingWithdrawals=computed(()=>withdrawals.value.filter(w=>['pending','approved'].includes(w.status)));
function money(v:any,c='GHS'){return `${c} ${Number(v||0).toFixed(2)}`}
async function load(){loading.value=true;error.value='';try{strategy.value=await apiFetch('/admin/rewards/strategy');platformPercent.value=strategy.value.platformSharePercent;poolPercent.value=strategy.value.tipsterPoolPercent;periods.value=await apiFetch('/admin/rewards/periods');rewards.value=await apiFetch('/admin/rewards');withdrawals.value=await apiFetch('/admin/withdrawals');revenue.value=await apiFetch('/admin/rewards/revenue?days=365')}catch(e:any){error.value=e.message||'Unable to load reward centre.'}finally{loading.value=false}}
async function saveStrategy(){savingStrategy.value=true;error.value='';try{strategy.value=await apiFetch('/admin/rewards/strategy',{method:'PATCH',body:JSON.stringify({platformSharePercent:Number(platformPercent.value),tipsterPoolPercent:Number(poolPercent.value),minSettledPredictions:Number(strategy.value.minSettledPredictions),minMonthlySettledPredictions:Number(strategy.value.minMonthlySettledPredictions||5),minWithdrawal:Number(strategy.value.minWithdrawal||10),currency:strategy.value.currency||'GHS'})});await load()}catch(e:any){error.value=e.message||'Unable to save reward strategy.'}finally{savingStrategy.value=false}}
async function calculate(){calculating.value=true;error.value='';try{await apiFetch('/admin/rewards/periods/calculate',{method:'POST',body:JSON.stringify({month:month.value,platformSharePercent:Number(platformPercent.value),tipsterPoolPercent:Number(poolPercent.value)})});await load()}catch(e:any){error.value=e.message||'Unable to calculate reward period.'}finally{calculating.value=false}}
async function approve(id:string){try{await apiFetch(`/admin/rewards/${id}/approve`,{method:'PATCH'});await load()}catch(e:any){error.value=e.message}}
async function available(id:string){try{await apiFetch(`/admin/rewards/${id}/available`,{method:'PATCH'});await load()}catch(e:any){error.value=e.message}}
async function withdrawal(id:string,status:string){try{await apiFetch(`/admin/withdrawals/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template>
<v-row>
  <v-col cols="12">
    <v-card class="reward-hero" elevation="0"><v-card-text class="pa-7"><div class="d-flex justify-space-between align-start flex-wrap ga-5"><div><div class="text-overline text-white-50">BraTipsters monetization</div><h1 class="text-h4 text-white font-weight-bold mb-2">Tipster Rewards & Revenue</h1><p class="text-body-1 text-white opacity-80 mb-0">70% stays with BraTipsters. 30% of collected subscription revenue funds the performance pool.</p></div><v-chip color="white" variant="outlined">NO P2P WAGERING</v-chip></div></v-card-text></v-card>
  </v-col>
  <v-col cols="12" md="3"><v-card><v-card-text><div class="text-caption">Platform share</div><div class="text-h5 font-weight-bold">{{platformPercent}}%</div><div class="text-caption">BraTipsters revenue</div></v-card-text></v-card></v-col>
  <v-col cols="12" md="3"><v-card><v-card-text><div class="text-caption">Tipster pool</div><div class="text-h5 font-weight-bold">{{poolPercent}}%</div><div class="text-caption">Performance rewards</div></v-card-text></v-card></v-col>
  <v-col cols="12" md="3"><v-card><v-card-text><div class="text-caption">Eligibility</div><div class="text-h5 font-weight-bold">{{strategy.minSettledPredictions}}</div><div class="text-caption">settled predictions minimum</div></v-card-text></v-card></v-col>
  <v-col cols="12" md="3"><v-card><v-card-text><div class="text-caption">Collected revenue</div><div class="text-h5 font-weight-bold">{{money(revenue.total.amount, revenue.byCurrency?.[0]?._id||strategy.currency)}}</div><div class="text-caption">{{revenue.total.count||0}} paid invoices</div></v-card-text></v-card></v-col>

  <v-col cols="12"><v-card><v-card-title>Monthly pool calculator</v-card-title><v-card-subtitle>Calculate the previous month after Stripe revenue has settled. Rewards are created as pending until admin review.</v-card-subtitle><v-card-text><v-row><v-col cols="12" md="3"><v-text-field v-model="month" type="month" label="Reward month" /></v-col><v-col cols="12" md="3"><v-text-field v-model.number="platformPercent" type="number" min="0" max="100" label="Platform share %" /></v-col><v-col cols="12" md="3"><v-text-field v-model.number="poolPercent" type="number" min="0" max="100" label="Tipster pool %" /></v-col><v-col cols="12" md="3" class="d-flex align-center ga-2"><v-btn variant="outlined" :loading="savingStrategy" @click="saveStrategy">Save strategy</v-btn><v-btn color="primary" :loading="calculating" @click="calculate">Calculate rewards</v-btn></v-col></v-row><v-row class="mt-1"><v-col cols="12" md="3"><v-text-field v-model.number="strategy.minSettledPredictions" type="number" min="1" label="Lifetime settled minimum" /></v-col><v-col cols="12" md="3"><v-text-field v-model.number="strategy.minMonthlySettledPredictions" type="number" min="1" label="Monthly settled minimum" /></v-col><v-col cols="12" md="3"><v-text-field v-model.number="strategy.minWithdrawal" type="number" min="1" label="Minimum withdrawal" /></v-col><v-col cols="12" md="3"><v-text-field v-model="strategy.currency" label="Wallet currency" /></v-col></v-row><v-alert type="info" variant="tonal">Formula: 40% win rate · 25% volume · 15% consistency · 10% ROI · 10% discipline. Lifetime performance is used for the long-term score; monthly volume keeps the pool focused on active tipsters.</v-alert></v-card-text></v-card></v-col>

  <v-col cols="12"><v-card><v-card-title>Reward periods</v-card-title><v-card-text><v-table density="comfortable"><thead><tr><th>Month</th><th>Revenue</th><th>Pool</th><th>Platform</th><th>Allocated</th><th>Status</th></tr></thead><tbody><tr v-for="p in periods" :key="p._id"><td>{{p.label}}</td><td>{{money(p.grossRevenue,p.currency)}}</td><td>{{money(p.tipsterPoolAmount,p.currency)}} ({{p.tipsterPoolPercent}}%)</td><td>{{money(p.platformRevenueAmount,p.currency)}} ({{p.platformSharePercent}}%)</td><td>{{money(p.allocatedAmount,p.currency)}}</td><td><v-chip size="small" variant="tonal">{{p.status}}</v-chip></td></tr><tr v-if="!periods.length"><td colspan="6" class="text-center py-6">No reward periods calculated yet.</td></tr></tbody></v-table></v-card-text></v-card></v-col>

  <v-col cols="12"><v-card><v-card-title>Tipster performance rewards <v-chip class="ml-2" size="small">{{eligibleRewards.length}} eligible</v-chip></v-card-title><v-card-text><v-table density="comfortable"><thead><tr><th>Tipster</th><th>Settled</th><th>Monthly</th><th>Win rate</th><th>ROI</th><th>Score</th><th>Share</th><th>Reward</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="r in rewards" :key="r._id"><td><b>{{r.tipsterId?.username||r.tipsterId?.userId?.name||'Tipster'}}</b><div class="text-caption">{{r.periodId?.label}}</div></td><td>{{r.settledPredictions}}</td><td>{{r.monthlySettledPredictions}}</td><td>{{Number(r.winRate||0).toFixed(1)}}%</td><td>{{Number(r.roi||0).toFixed(1)}}%</td><td>{{Number(r.performanceScore||0).toFixed(3)}}</td><td>{{Number(r.sharePercent||0).toFixed(2)}}%</td><td><b>{{money(r.amount,r.currency)}}</b></td><td><v-chip size="small" variant="tonal">{{r.status}}</v-chip></td><td><v-btn v-if="r.status==='pending'" size="small" @click="approve(r._id)">Approve</v-btn><v-btn v-if="r.status==='approved'" size="small" color="success" @click="available(r._id)">Release</v-btn></td></tr><tr v-if="!rewards.length"><td colspan="10" class="text-center py-6">No rewards yet.</td></tr></tbody></v-table></v-card-text></v-card></v-col>

  <v-col cols="12"><v-card><v-card-title>Tipster withdrawals <v-chip class="ml-2" size="small">{{pendingWithdrawals.length}} open</v-chip></v-card-title><v-card-subtitle>Manual payout workflow. No user betting wallet is involved.</v-card-subtitle><v-card-text><v-table density="comfortable"><thead><tr><th>Tipster</th><th>Amount</th><th>Method</th><th>Requested</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="w in withdrawals" :key="w._id"><td>{{w.tipsterId?.username||w.tipsterId?.userId?.name||'Tipster'}}</td><td><b>{{money(w.amount,w.currency)}}</b></td><td class="text-capitalize">{{w.method.replace('_',' ')}}</td><td>{{new Date(w.createdAt).toLocaleString()}}</td><td><v-chip size="small" variant="tonal">{{w.status}}</v-chip></td><td><v-btn v-if="w.status==='pending'" size="small" @click="withdrawal(w._id,'approved')">Approve</v-btn><v-btn v-if="['pending','approved'].includes(w.status)" size="small" color="success" class="ml-1" @click="withdrawal(w._id,'paid')">Mark paid</v-btn><v-btn v-if="['pending','approved'].includes(w.status)" size="small" color="error" variant="text" class="ml-1" @click="withdrawal(w._id,'rejected')">Reject</v-btn></td></tr><tr v-if="!withdrawals.length"><td colspan="6" class="text-center py-6">No withdrawal requests.</td></tr></tbody></v-table></v-card-text></v-card></v-col>

  <v-col cols="12" v-if="error"><v-alert type="error" variant="tonal">{{error}}</v-alert></v-col>
</v-row>
</template>
<style scoped>
.reward-hero{background:linear-gradient(135deg,#101a2e,#182641);border-radius:18px}.text-white-50{color:rgba(255,255,255,.62)!important}
</style>
